[package]
name = "bdf-parser"
version = "0.1.0"
authors = ["James Waples <jamwaffles@gmail.com>"]

[dependencies]
nom = "4.0.0-beta3"
nom_locate = "0.1.1"

[dev-dependencies]
chardet = "0.2.4"
encoding = "0.2.33"
