[package]
name = "test-bdf-parser"
version = "0.1.0"
authors = ["Ralf Fuest <mail@rfuest.de>"]
edition = "2018"

[dev-dependencies]
chardet = "0.2.4"
encoding = "0.2.33"
bdf-parser = { path = "../../bdf-parser" }
